apiVersion: apps/v1
kind: Deployment
metadata:
  name: authSystem-backend
  namespace: auth-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authSystem-backend
  template:
    metadata:
      labels:
        app: authSystem-backend
    spec:
      containers:
        - name: authSystem-backend
          image: authsystem-backend:v1.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-system-config
            - secretRef:
                name: auth-system-secret