apiVersion: apps/v1
kind: Deployment
metadata:
  name: authsystem-backend
  namespace: auth-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authsystem-backend
  template:
    metadata:
      labels:
        app: authsystem-backend
    spec:
      containers:
        - name: authsystem-backend
          image: authsystem-backend:v1.0.1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-system-config
            - secretRef:
                name: auth-system-secret
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 2
          startupProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 10
            periodSeconds: 5