apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-system-config
  namespace: auth-system

data:
  PORT: "5000"
  NODE_ENV: "development"
  CLIENT_URL: "http://localhost:3000"
  BASE_URL: "http://localhost:5000"
  MONGO_URI: "mongodb://mongo-service:27017/authsystem"