apiVersion: v1
kind: Secret

metadata:
  name: auth-system-secret
  namespace: auth-system

type: Opaque

stringData:
  JWT_SECRET: "<YOUR_JWT_SECRET>"
  JWT_REFRESH_SECRET: "<YOUR_REFRESH_SECRET>"
  EMAIL_USER: "<YOUR_EMAIL>"
  EMAIL_PASS: "<YOUR_PASSWORD>"